host:
  http_port: '8080'
  cover_cache:
    directory: cache_covers
    size: 2000
  audio_cache:
    directory: cache_audio
    size: 500
  logger:
    buffer_capacity: 200
    enable_console: true
    min_level: INFO
devices:
  mediarenderer:
    testdevice:
      udn: 32779579-36ed-4001-a7c4-b19fccbe2009
