[workspace]
resolver = "3"
members = ["PMOMusic", "pmoupnp", "pmomediarenderer", "pmomediaserver", "pmoconfig", "pmoutils", "pmodidl", "pmoserver", "pmoapp", "pmocache", "pmocovers", "pmoaudiocache", "pmoaudio", "pmoqobuz", "pmoparadise", "pmosource", "pmoplaylist"]
