[package]
name = "pmoplaylist"
version = "0.1.0"
edition = "2024"

[dependencies]
pmodidl = { path = "../pmodidl" }
tokio = { version = "1.42.0", features = ["sync", "time", "macros", "rt", "rt-multi-thread"] }
serde = { version = "1.0.228", features = ["derive"] }
