host:
  http_port: '8080'
  cover_cache:
    directory: cache_covers
    size: 2000
  audio_cache:
    directory: cache_audio
    size: 500
  logger:
    buffer_capacity: 200
    enable_console: true
    min_level: INFO
playlists:
  directory: playlists
devices:
  mediarenderer:
    pmo_mediarenderer:
      udn: f77de90b-3a4a-408c-8462-3308ad500744
  mediaserver:
    pmo_mediaserver:
      udn: 88b84e76-4de0-4ee6-b794-99cc4a278cc9
