[package]
name = "pmometadata"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
paste = "1"
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
